// This file is generated by Velite

import type config from '../velite.config.ts'

type Collections = typeof config.collections

export type Docs = Collections['docs']['schema']['_output']
export declare const docs: Docs[]
